/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // Garantir que as classes order sejam geradas
    "order-1",
    "order-2",
    "sm:order-1",
    "sm:order-2",
    "lg:order-1",
    "lg:order-2",
    // Classes margin essenciais
    "mt-10",
    "mb-10",
    "lg:mt-10",
    "lg:mb-10",
    "sm:mt-10",
    "sm:mb-10",
    "mt-8",
    "mb-8",
    "lg:mt-8",
    "lg:mb-8",
    "sm:mt-8",
    "sm:mb-8",
    // Classes max-w dinâmicas para FeatureSection
    "max-w-[300px]",
    "max-w-[400px]",
    "max-w-[500px]",
    "max-w-[600px]",
    "max-w-[700px]",
    "max-w-[800px]",
    "max-w-[900px]",
    "max-w-[1000px]",
    "lg:max-w-[300px]",
    "lg:max-w-[400px]",
    "lg:max-w-[500px]",
    "lg:max-w-[600px]",
    "lg:max-w-[700px]",
    "lg:max-w-[800px]",
    "lg:max-w-[900px]",
    "lg:max-w-[1000px]",
  ],
  theme: {
    extend: {
      fontSize: {
        xs: ["0.75rem", { lineHeight: "1rem" }],
        sm: ["0.875rem", { lineHeight: "1.25rem" }],
        base: ["1rem", { lineHeight: "1.5rem" }],
        lg: ["1.125rem", { lineHeight: "1.75rem" }],
        xl: ["1.25rem", { lineHeight: "1.75rem" }],
        "2xl": ["1.5rem", { lineHeight: "2rem" }],
        "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
        "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
        "5xl": ["3rem", { lineHeight: "1" }],
        "6xl": ["3.75rem", { lineHeight: "1" }],
        "7xl": ["4.5rem", { lineHeight: "1" }],
        "8xl": ["6rem", { lineHeight: "1" }],
        "9xl": ["8rem", { lineHeight: "1" }],
      },
      textIndent: {
        8: "2rem", // Adiciona indent-8 (32px)
      },
    },
  },
  plugins: [],
};
